name: "Configure Cache"
description: "Download dependencies and save required cache"

runs:
  using: "composite"
  steps:
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Make gradle executable
      shell: bash
      run: chmod +x ./gradlew

    - name: Download Depdendencies
      shell: bash
      env:
        GRADLE_OPTS: "-Xms1g -Xmx4608M -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.daemon=false -Dorg.gradle.caching=false -Dorg.gradle.configureondemand=true -Dfile.encoding=UTF-8 -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false"
      run: |
        ./gradlew dependencies persistent-cookie-jar-okhttp:dependencies persistent-cookie-jar-okhttp:androidDependencies --no-parallel --no-daemon --max-workers 3
