---
name: Development build


on:
  pull_request:
    branches:
      - 'master'

env:
  REPO_ARTIFACTS_URL: ${{ secrets.REPO_ARTIFACTS_URL }}
  REPO_USERID: ${{ secrets.REPO_USERID }}
  REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/config-action

      - name: Run Unit Tests
        run: ./gradlew persistent-cookie-jar-okhttp:test
