---
name: Development build


on:
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/config-action

      - name: Run Unit Tests
        run: ./gradlew persistent-cookie-jar-okhttp:test
