---
name: Publish persistent-cookie-jar-okhttp Library

on:
  push:
    tags:
      - 'v**'
env:
  REPO_PUBLISH_URL: ${{ secrets.PARAMOUNT_NEXUS_RELEASE_URL }}
  REPO_PUBLISH_USERID: ${{ secrets.PARAMOUNT_NEXUS_USER }}
  REPO_PUBLISH_PW: ${{ secrets.PARAMOUNT_NEXUS_PW }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/config-action

      - name: Run Unit Tests
        run: ./gradlew persistent-cookie-jar-okhttp:test

      - name: Publish Library
        run: ./gradlew  --stacktrace -PrepoPublishURL=$REPO_PUBLISH_URL -PrepoPublishUsername=$REPO_PUBLISH_USERID -PrepoPublishPassword=$REPO_PUBLISH_PW clean persistent-cookie-jar-okhttp:assembleRelease publish
