---
name: Publish persistent-cookie-jar-okhttp Library

on:
  push:
    tags:
      - 'v**'
    branches:
     - 'datastore-kotlin-impl'
env:
  NEXUS_URL: ${{ secrets.NEXUS_URL }}
  NEXUS_USERID: ${{ secrets.NEXUS_USERID }}
  NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/config-action

      - name: Run Unit Tests
        run: ./gradlew persistent-cookie-jar-okhttp:test

      - name: Publish Library
        run: ./gradlew  --stacktrace -PnexusURL=$NEXUS_URL -PnexusUserName=$NEXUS_USERID -PnexusUserPassword=$NEXUS_PASSWORD clean persistent-cookie-jar-okhttp:assembleRelease publish
