---
name: Publish persistent-cookie-jar-okhttp Library

on:
  push:
    tags:
      - 'v**'
    branches:
     - 'datastore-kotlin-impl'
env:
  REPO_ARTIFACTS_URL: ${{ secrets.REPO_ARTIFACTS_URL }}
  REPO_PUBLISH_URL: ${{ secrets.REPO_PUBLISH_URL }}
  REPO_USERID: ${{ secrets.REPO_USERID }}
  REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/config-action

      - name: Run Unit Tests
        run: ./gradlew persistent-cookie-jar-okhttp:test

      - name: Publish Library
        run: ./gradlew  --stacktrace -PrepoPublishURL=$REPO_PUBLISH_URL -PrepoUserName=$REPO_USERID -PrepoUserPassword=$REPO_PASSWORD clean persistent-cookie-jar-okhttp:assembleRelease publish
